### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by DoomZoe** [Hyper-Beast/91porn#7]
**cookie是这样**
cookie="__utmz=50351329.1628865074.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=50351329.2068558348.1628865074.1631108063.1634045580.7; __utmb=50351329.0.10.1634045580; __utmc=50351329; CLIPSHARE=m04irg461foff2tlqqejst3pir"

**运行.bat**

D:\Program Files\91porn-main>python run.py
请输入你想抓取的总页数:1
a1  解析  1  页  http://807.workgreat17.live//v.php?category=rf&viewtype=basic&p
age=1
Exception in thread a1:
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_
conn
    conn = connection.create_connection(
  File "C:\Python39\lib\site-packages\urllib3\util\connection.py", line 96, in c
reate_connection
    raise err
  File "C:\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in c
reate_connection
    sock.connect(sa)
OSError: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in u
rlopen
    httplib_response = self._make_request(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 394, in _
make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 234, in reque
st
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)

  File "C:\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 200, in conne
ct
    conn = self._new_conn()
  File "C:\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_
conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object
 at 0x000000ABC373CA90>: Failed to establish a new connection: [WinError 10051]
向一个无法连接的网络尝试了一个套接字操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 783, in u
rlopen
    return self.urlopen(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 783, in u
rlopen
    return self.urlopen(
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 783, in u
rlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "C:\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in u
rlopen
    retries = retries.increment(
  File "C:\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in incre
ment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='807.workgreat17.live'
, port=80): Max retries exceeded with url: //v.php?category=rf&viewtype=basic&pa
ge=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at
 0x000000ABC373CA90>: Failed to establish a new connection: [WinError 10051] 向
一个无法连接的网络尝试了一个套接字操作。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files\91porn-main\parse_list.py", line 29, in enter
    parseList(url)
  File "D:\Program Files\91porn-main\parse_list.py", line 10, in parseList
    m = common.visit(url)
  File "D:\Program Files\91porn-main\common.py", line 65, in visit
    html = s.get(url, headers=headers, cookies=cookies, stream=True).content
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 542, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='807.workgreat17.li
ve', port=80): Max retries exceeded with url: //v.php?category=rf&viewtype=basic
&page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object
 at 0x000000ABC373CA90>: Failed to establish a new connection: [WinError 10051]
向一个无法连接的网络尝试了一个套接字操作。'))
网页解析完毕,下一步请运行downloadm3u8.py

D:\Program Files\91porn-main>python downloadm3u8.py
Traceback (most recent call last):
  File "D:\Program Files\91porn-main\downloadm3u8.py", line 8, in <module>
    with open(os.getcwd()+"\\url.txt", "r",encoding='utf-8') as urls:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Program Files\\91po
rn-main\\url.txt'

D:\Program Files\91porn-main>pause
请按任意键继续. . .

**更换common.py中的url，运行结果同上**
请教下哪里配置有问题

**Comment by Hyper-Beast** [comment]
downloadm3u8的第6行和common的第11行两个文件的都要改，如果还是这样你就看看自己能不能正常打开http://807.workgreat17.live/v.php?category=rf&viewtype=basic&page=1 这个网站
